name: bugpt
description: "A new Flutter project."

publish_to: 'none' 

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  google_fonts: ^6.1.0
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true
  
  assets:
    - assets/
